package com.tuempresa.miapp.model
data class Country(
    val name: String,
    val dialCode: String,
    val emoji: String
)
val countries = listOf(
    Country("Afganistán", "+93", "🇦🇫"),
    Country("Albania", "+355", "🇦🇱"),
    Country("Alemania", "+49", "🇩🇪"),
    Country("Andorra", "+376", "🇦🇩"),
    Country("Angola", "+244", "🇦🇴"),
    Country("Anguila", "+1-264", "🇦🇮"),
    Country("Antigua y Barbuda", "+1-268", "🇦🇬"),
    Country("Arabia Saudita", "+966", "🇸🇦"),
    Country("Argelia", "+213", "🇩🇿"),
    Country("Argentina", "+54", "🇦🇷"),
    Country("Armenia", "+374", "🇦🇲"),
    Country("Aruba", "+297", "🇦🇼"),
    Country("Australia", "+61", "🇦🇺"),
    Country("Austria", "+43", "🇦🇹"),
    Country("Azerbaiyán", "+994", "🇦🇿"),
    Country("Bahamas", "+1-242", "🇧🇸"),
    Country("Bahrein", "+973", "🇧🇭"),
    Country("Bangladesh", "+880", "🇧🇩"),
    Country("Barbados", "+1-246", "🇧🇧"),
    Country("Belarús", "+375", "🇧🇾"),
    Country("Bélgica", "+32", "🇧🇪"),
    Country("Belice", "+501", "🇧🇿"),
    Country("Benín", "+229", "🇧🇯"),
    Country("Bermudas", "+1-441", "🇧🇲"),
    Country("Bhután", "+975", "🇧🇹"),
    Country("Bolivia", "+591", "🇧🇴"),
    Country("Bosnia y Herzegovina", "+387", "🇧🇦"),
    Country("Botsuana", "+267", "🇧🇼"),
    Country("Brasil", "+55", "🇧🇷"),
    Country("Brunéi", "+673", "🇧🇳"),
    Country("Bulgaria", "+359", "🇧🇬"),
    Country("Burkina Faso", "+226", "🇧🇫"),
    Country("Burundi", "+257", "🇧🇮"),
    Country("Camboya", "+855", "🇰🇭"),
    Country("Camerún", "+237", "🇨🇲"),
    Country("Canadá", "+1", "🇨🇦"),
    Country("Catar", "+974", "🇶🇦"),
    Country("Chad", "+235", "🇹🇩"),
    Country("Chile", "+56", "🇨🇱"),
    Country("China", "+86", "🇨🇳"),
    Country("Chipre", "+357", "🇨🇾"),
    Country("Colombia", "+57", "🇨🇴"),
    Country("Comoras", "+269", "🇰🇲"),
    Country("Congo", "+242", "🇨🇬"),
    Country("Corea del Norte", "+850", "🇰🇵"),
    Country("Corea del Sur", "+82", "🇰🇷"),
    Country("Costa de Marfil", "+225", "🇨🇮"),
    Country("Costa Rica", "+506", "🇨🇷"),
    Country("Croacia", "+385", "🇭🇷"),
    Country("Cuba", "+53", "🇨🇺"),
    Country("Curazao", "+599", "🇨🇼"),
    Country("Dinamarca", "+45", "🇩🇰"),
    Country("Djibouti", "+253", "🇩🇯"),
    Country("Dominica", "+1-767", "🇩🇲"),
    Country("Ecuador", "+593", "🇪🇨"),
    Country("Egipto", "+20", "🇪🇬"),
    Country("El Salvador", "+503", "🇸🇻"),
    Country("Emiratos Árabes Unidos", "+971", "🇦🇪"),
    Country("Eritrea", "+291", "🇪🇷"),
    Country("Eslovaquia", "+421", "🇸🇰"),
    Country("Eslovenia", "+386", "🇸🇮"),
    Country("España", "+34", "🇪🇸"),
    Country("Estados Unidos", "+1", "🇺🇸"),
    Country("Estonia", "+372", "🇪🇪"),
    Country("Etiopía", "+251", "🇪🇹"),
    Country("Fiyi", "+679", "🇫🇯"),
    Country("Filipinas", "+63", "🇵🇭"),
    Country("Finlandia", "+358", "🇫🇮"),
    Country("Francia", "+33", "🇫🇷"),
    Country("Gabón", "+241", "🇬🇦"),
    Country("Gambia", "+220", "🇬🇲"),
    Country("Georgia", "+995", "🇬🇪"),
    Country("Ghana", "+233", "🇬🇭"),
    Country("Gibraltar", "+350", "🇬🇮"),
    Country("Granada", "+1-473", "🇬🇩"),
    Country("Grecia", "+30", "🇬🇷"),
    Country("Groenlandia", "+299", "🇬🇱"),
    Country("Guadalupe", "+590", "🇬🇵"),
    Country("Guam", "+1-671", "🇬🇺"),
    Country("Guatemala", "+502", "🇬🇹"),
    Country("Guayana Francesa", "+594", "🇬🇫"),
    Country("Guernesey", "+44-1481", "🇬🇬"),
    Country("Guinea", "+224", "🇬🇳"),
    Country("Guinea-Bisáu", "+245", "🇬🇼"),
    Country("Guinea Ecuatorial", "+240", "🇬🇶"),
    Country("Guyana", "+592", "🇬🇾"),
    Country("Haití", "+509", "🇭🇹"),
    Country("Honduras", "+504", "🇭🇳"),
    Country("Hong Kong", "+852", "🇭🇰"),
    Country("Hungría", "+36", "🇭🇺"),
    Country("India", "+91", "🇮🇳"),
    Country("Indonesia", "+62", "🇮🇩"),
    Country("Irak", "+964", "🇮🇶"),
    Country("Irán", "+98", "🇮🇷"),
    Country("Irlanda", "+353", "🇮🇪"),
    Country("Isla de Man", "+44-1624", "🇮🇲"),
    Country("Islas Caimán", "+1-345", "🇰🇾"),
    Country("Islas Cook", "+682", "🇨🇰"),
    Country("Islas Feroe", "+298", "🇫🇴"),
    Country("Islas Malvinas", "+500", "🇫🇰"),
    Country("Islas Marianas del Norte", "+1-670", "🇲🇵"),
    Country("Islas Marshall", "+692", "🇲🇭"),
    Country("Islas Salomón", "+677", "🇸🇧"),
    Country("Islas Turcas y Caicos", "+1-649", "🇹🇨"),
    Country("Islas Vírgenes Británicas", "+1-284", "🇻🇬"),
    Country("Israel", "+972", "🇮🇱"),
    Country("Italia", "+39", "🇮🇹"),
    Country("Jamaica", "+1-876", "🇯🇲"),
    Country("Japón", "+81", "🇯🇵"),
    Country("Jordania", "+962", "🇯🇴"),
    Country("Kazajistán", "+7", "🇰🇿"),
    Country("Kenia", "+254", "🇰🇪"),
    Country("Kirguistán", "+996", "🇰🇬"),
    Country("Kiribati", "+686", "🇰🇮"),
    Country("Kuwait", "+965", "🇰🇼"),
    Country("Laos", "+856", "🇱🇦"),
    Country("Lesoto", "+266", "🇱🇸"),
    Country("Letonia", "+371", "🇱🇻"),
    Country("Líbano", "+961", "🇱🇧"),
    Country("Liberia", "+231", "🇱🇷"),
    Country("Libia", "+218", "🇱🇾"),
    Country("Liechtenstein", "+423", "🇱🇮"),
    Country("Lituania", "+370", "🇱🇹"),
    Country("Luxemburgo", "+352", "🇱🇺"),
    Country("Macao", "+853", "🇲🇴"),
    Country("Macedonia del Norte", "+389", "🇲🇰"),
    Country("Madagascar", "+261", "🇲🇬"),
    Country("Malasia", "+60", "🇲🇾"),
    Country("Malaui", "+265", "🇲🇼"),
    Country("Maldivas", "+960", "🇲🇻"),
    Country("Mali", "+223", "🇲🇱"),
    Country("Malta", "+356", "🇲🇹"),
    Country("Marruecos", "+212", "🇲🇦"),
    Country("Martinica", "+596", "🇲🇶"),
    Country("Mauricio", "+230", "🇲🇺"),
    Country("Mauritania", "+222", "🇲🇷"),
    Country("Mayotte", "+262", "🇾🇹"),
    Country("México", "+52", "🇲🇽"),
    Country("Micronesia", "+691", "🇫🇲"),
    Country("Moldavia", "+373", "🇲🇩"),
    Country("Mónaco", "+377", "🇲🇨"),
    Country("Mongolia", "+976", "🇲🇳"),
    Country("Montenegro", "+382", "🇲🇪"),
    Country("Montserrat", "+1-664", "🇲🇸"),
    Country("Mozambique", "+258", "🇲🇿"),
    Country("Myanmar", "+95", "🇲🇲"),
    Country("Namibia", "+264", "🇳🇦"),
    Country("Nauru", "+674", "🇳🇷"),
    Country("Nepal", "+977", "🇳🇵"),
    Country("Nicaragua", "+505", "🇳🇮"),
    Country("Níger", "+227", "🇳🇪"),
    Country("Nigeria", "+234", "🇳🇬"),
    Country("Niue", "+683", "🇳🇺"),
    Country("Noruega", "+47", "🇳🇴"),
    Country("Nueva Caledonia", "+687", "🇳🇨"),
    Country("Nueva Zelanda", "+64", "🇳🇿"),
    Country("Omán", "+968", "🇴🇲"),
    Country("Países Bajos", "+31", "🇳🇱"),
    Country("Pakistán", "+92", "🇵🇰"),
    Country("Palaos", "+680", "🇵🇼"),
    Country("Palestina", "+970", "🇵🇸"),
    Country("Panamá", "+507", "🇵🇦"),
    Country("Papúa Nueva Guinea", "+675", "🇵🇬"),
    Country("Paraguay", "+595", "🇵🇾"),
    Country("Perú", "+51", "🇵🇪"),
    Country("Polinesia Francesa", "+689", "🇵🇫"),
    Country("Polonia", "+48", "🇵🇱"),
    Country("Portugal", "+351", "🇵🇹"),
    Country("Puerto Rico", "+1-787", "🇵🇷"),
    Country("Qatar", "+974", "🇶🇦"),
    Country("Reino Unido", "+44", "🇬🇧"),
    Country("República Centroafricana", "+236", "🇨🇫"),
    Country("República Checa", "+420", "🇨🇿"),
    Country("República Dominicana", "+1-809", "🇩🇴"),
    Country("Reunión", "+262", "🇷🇪"),
    Country("Ruanda", "+250", "🇷🇼"),
    Country("Rumanía", "+40", "🇷🇴"),
    Country("Rusia", "+7", "🇷🇺"),
    Country("Samoa", "+685", "🇼🇸"),
    Country("Samoa Americana", "+1-684", "🇦🇸"),
    Country("San Cristóbal y Nieves", "+1-869", "🇰🇳"),
    Country("San Marino", "+378", "🇸🇲"),
    Country("San Vicente y las Granadinas", "+1-784", "🇻🇨"),
    Country("Santa Elena", "+290", "🇸🇭"),
    Country("Santa Lucía", "+1-758", "🇱🇨"),
    Country("Santo Tomé y Príncipe", "+239", "🇸🇹"),
    Country("Senegal", "+221", "🇸🇳"),
    Country("Serbia", "+381", "🇷🇸"),
    Country("Seychelles", "+248", "🇸🇨"),
    Country("Sierra Leona", "+232", "🇸🇱"),
    Country("Singapur", "+65", "🇸🇬"),
    Country("Siria", "+963", "🇸🇾"),
    Country("Somalia", "+252", "🇸🇴"),
    Country("Sri Lanka", "+94", "🇱🇰"),
    Country("Sudáfrica", "+27", "🇿🇦"),
    Country("Sudán", "+249", "🇸🇩"),
    Country("Sudán del Sur", "+211", "🇸🇸"),
    Country("Suecia", "+46", "🇸🇪"),
    Country("Suiza", "+41", "🇨🇭"),
    Country("Surinam", "+597", "🇸🇷"),
    Country("Tailandia", "+66", "🇹🇭"),
    Country("Taiwán", "+886", "🇹🇼"),
    Country("Tanzania", "+255", "🇹🇿"),
    Country("Tayikistán", "+992", "🇹🇯"),
    Country("Timor Oriental", "+670", "🇹🇱"),
    Country("Togo", "+228", "🇹🇬"),
    Country("Tokelau", "+690", "🇹🇰"),
    Country("Tonga", "+676", "🇹🇴"),
    Country("Trinidad y Tobago", "+1-868", "🇹🇹"),
    Country("Túnez", "+216", "🇹🇳"),
    Country("Turkmenistán", "+993", "🇹🇲"),
    Country("Turquía", "+90", "🇹🇷"),
    Country("Tuvalu", "+688", "🇹🇻"),
    Country("Ucrania", "+380", "🇺🇦"),
    Country("Uganda", "+256", "🇺🇬"),
    Country("Uruguay", "+598", "🇺🇾"),
    Country("Uzbekistán", "+998", "🇺🇿"),
    Country("Vanuatu", "+678", "🇻🇺"),
    Country("Vaticano", "+379", "🇻🇦"),
    Country("Venezuela", "+58", "🇻🇪"),
    Country("Vietnam", "+84", "🇻🇳"),
    Country("Wallis y Futuna", "+681", "🇼🇫"),
    Country("Yemen", "+967", "🇾🇪"),
    Country("Yibuti", "+253", "🇩🇯"),
    Country("Zambia", "+260", "🇿🇲"),
    Country("Zimbabue", "+263", "🇿🇼")
)
